#+title: mouthpiecer-cli

* About

*mouthpiecer-cli* is a Python based command line interface to a [[https://www.knack.com][Knack]] database.

The Mouthpiecer Knack front end can be found here: [[https://aleksozolins.knack.com/mouthpiecer#home/]]

- The app is meant for individual users to manage their French Horn mouthpiece collection (really).
- Users can also view the collections of other "mouthpiecers" and can arrange mouthpiece trades as well.
- For now, some features have been removed from the front end and will be re-introduced as the cli develops.

Ultimately, the cli should exactly mirror the feature-set of the web front end.

* Compatibility

- [X] macOS
- [X] Linux
- [ ] Windown (not currently supported)

* Dependencies

For now, any dependencies have to be installed manually with =pip=.

- [[https://pandas.pydata.org/][pandas - Python Data Analisys Library]]
- termcolor

* Known issues

- [ ] After adding a new user, if you elect not to save your first mouthpiece with [n], an error is returned and the program terminates.
- [RESOLVED] When selecting a mouthpiece to delete, if an invalid selection is made, the program will terminate with an error.
- [RESOLVED] While adding a mouthpiece, if you enter an invalid menu selection for type, threads, or finish, and then press "0" at the "My mouthpieces" menu, something strange happens.

* Todos

- [ ] Installation shell script
- [ ] Increase spacing between dataframe columns
- [ ] Change "Make" selection to choice by int
- [ ] Prefill inputs during edit operation
- [ ] Move project to org using babel
- [ ] Assign connection from account to mouthpiecer when adding new user
- [ ] Pagination
- [ ] Add note to mouthpiece
- [ ] View mouthpiece details option with note
- [X] Edit mouthpiece operation
- [X] Add conditional threading input for adding mouthpiece
- [X] Error when a non-integer value is entered for an integer menu
- [X] Add thread field to My Mouthpieces view
- [X] Problem listing mouthpieces when there are none
  reference [[https://stackoverflow.com/questions/15943769/how-do-i-get-the-row-count-of-a-pandas-dataframe][this]]
- [X] Add confirm prompts to operations
- [X] Normalize spacing of all operations
- [X] Spruce up the interface with more color
- [X] Colored output
- [X] View based calls (as opposed to object based calls) once logged in
- [X] Error handling
- [X] Format incoming JSON into table (list mouthpieces)
- [X] Add log out option
- [X] Do not allow mouthpiece operation if not logged in
- [X] Logged in indicator (you are logged in as...)
